#.streamlit/config.toml
[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[theme]
base = "light"
primaryColor = "#8F00FF"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f0f5"
textColor = "#262730"
font = "sans serif"

